#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors','On');

require_once __DIR__ . "/functions.php";


$version = getLastTag();
echo $version;

list($v, $r, $h) = extractVersion($version);

@list($script, $flow, $action, $msg) = $argv;

if ('s' == $action) {
    $action = 'start';
}
if ('f' == $action) {
    $action = 'finish';
}

if ('r'==$flow) {
	$r = (int)$r;
	$r++;
	$h = 0;

	$version = concatVersion($v, $r, $h);
	$msg = '@rel ' . $msg;

    startRelease($version);

    finishRelease($version, $msg);

} elseif ('h'==$flow) {
	if ('start'==$action) {
		$h = (int)$h;
		$h++;
		$version = concatVersion($v, $r, $h);

		startHotFix($version);

		echo "Or:\n\tgitv h finish\n\n";

	} elseif ('finish'==$action) {
		$msg = '@fix ' . $msg;
    	$version = getCurrentHotFix();
		finishHotFix($version, $msg);
	} else {
		echo "Error: informe a ação start ou finish\n";
	}
} elseif ('b'==$flow) {
	if ('start'==$action) {
		$time = getTime();
		$version = concatVersion($v, $r, $h, $time);

		startHotFix($version);

		echo "Or:\n\tgitv b finish\n\n";

	} elseif ('finish'==$action) {
		$msg = '@fix ' . $msg;
    	$version = getCurrentHotFix();

		finishHotFix($version, $msg);
	} else {
		echo "Error: informe a ação start ou finish\n";
	}
} else {
	echo "Error: informe o tipo de flow r para RELEASE, b para BUILD ou h para HOTFIX\n";
}
